import { Resend } from 'resend'

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#x27;')
}

const resend = new Resend(process.env.RESEND_API_KEY)
const FROM = process.env.EMAIL_FROM ?? 'assessment@baawa.com'
const FOUNDER_EMAIL = process.env.FOUNDER_EMAIL ?? ''

// 1. Prospect acknowledgement (sent immediately after assessment completes)
export async function sendProspectAck(to: string): Promise<void> {
  try {
    await resend.emails.send({
      from: FROM,
      to,
      subject: 'We have your answers',
      html: `<p>Thank you for completing the assessment.</p>
<p>Our founder is reviewing your answers personally. You will hear from us within 48 hours.</p>`,
    })
  } catch (err) {
    throw new Error(`Failed to send prospect ACK to ${to}: ${String(err)}`)
  }
}

// 2. Founder notification (sent immediately with score)
export async function sendFounderNotification(
  prospectEmail: string,
  score: number,
  summary: string,
  biggestOpportunity: string,
  biggestRisk: string
): Promise<void> {
  if (!FOUNDER_EMAIL) return  // silently skip if not configured
  try {
    await resend.emails.send({
      from: FROM,
      to: FOUNDER_EMAIL,
      subject: `New assessment: ${escapeHtml(prospectEmail)} — Score ${score}/100`,
      html: `<h2>New Assessment Submission</h2>
<p><strong>From:</strong> ${escapeHtml(prospectEmail)}</p>
<p><strong>Score:</strong> ${score}/100</p>
<p><strong>Summary:</strong> ${escapeHtml(summary)}</p>
<p><strong>Biggest opportunity:</strong> ${escapeHtml(biggestOpportunity)}</p>
<p><strong>Biggest risk:</strong> ${escapeHtml(biggestRisk)}</p>
<p><a href="${process.env.DASHBOARD_URL ?? '#'}/dashboard/assessments">Review in dashboard →</a></p>`,
    })
  } catch (err) {
    throw new Error(`Failed to send founder notification for ${prospectEmail}: ${String(err)}`)
  }
}

// 3. Onboard email (sent when founder clicks Onboard in dashboard)
export async function sendOnboardEmail(to: string): Promise<void> {
  try {
    await resend.emails.send({
      from: FROM,
      to,
      subject: "We'd like to work with you",
      html: `<p>We have reviewed your answers and we would like to explore working together.</p>
<p>Our founder will be in touch within 24 hours to discuss next steps.</p>`,
    })
  } catch (err) {
    throw new Error(`Failed to send onboard email to ${to}: ${String(err)}`)
  }
}

// 4. Defer email (body generated by AI, passed in as plain text)
export async function sendDeferEmail(to: string, body: string): Promise<void> {
  try {
    await resend.emails.send({
      from: FROM,
      to,
      subject: 'Regarding your assessment',
      html: escapeHtml(body).split('\n').map((line) => `<p>${line}</p>`).join(''),
    })
  } catch (err) {
    throw new Error(`Failed to send defer email to ${to}: ${String(err)}`)
  }
}
